# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4acdc5b61c8a2985a7c8bae9a6a15b9b90ed6c7bedebc0ff1cacb0ef5ad6d03018938390ced411035d449f3a154b507a04f56fc9337d6b72b451b8cdda40b18

test:
  secret_key_base: 19a4ead0a521e6902a7e94c83bf826130584d8ce6a0d358520fe70afb9ca5582d13f702a00bd92e735cb0296cd564257266970870db711a2677b755d9b395358

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
